// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bin2lonlat
List bin2lonlat(IntegerVector bins, IntegerVector nrows);
RcppExport SEXP roc_bin2lonlat(SEXP binsSEXP, SEXP nrowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type bins(binsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nrows(nrowsSEXP);
    rcpp_result_gen = Rcpp::wrap(bin2lonlat(bins, nrows));
    return rcpp_result_gen;
END_RCPP
}
