// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bin2lonlat
List bin2lonlat(IntegerVector bins, IntegerVector nrows);
RcppExport SEXP roc_bin2lonlat(SEXP binsSEXP, SEXP nrowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type bins(binsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nrows(nrowsSEXP);
    __result = Rcpp::wrap(bin2lonlat(bins, nrows));
    return __result;
END_RCPP
}
