// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bin2lonlat
List bin2lonlat(IntegerVector bins, IntegerVector nrows);
RcppExport SEXP _roc_bin2lonlat(SEXP binsSEXP, SEXP nrowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type bins(binsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nrows(nrowsSEXP);
    rcpp_result_gen = Rcpp::wrap(bin2lonlat(bins, nrows));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_roc_bin2lonlat", (DL_FUNC) &_roc_bin2lonlat, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_roc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
