# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Longitude and latitude from bin number.  
#'
#' Generate longitude and latitude coordinates from bin number. 
#' @param bins bin number
#' @param nrows number of rows in this grid
#' @export
bin2lonlat <- function(bins, nrows) {
    .Call('roc_bin2lonlat', PACKAGE = 'roc', bins, nrows)
}

