# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Primary production
#' 
#' @export
prod_BeFa <- function(chla, irrad, stemp, daylength) {
    .Call(`_croc_prod_BeFa`, chla, irrad, stemp, daylength)
}

